# Author: Phil Aufdencamp

# This file will store the routines which are not active, but I want to keep 
# ahold of for future reference or inclusion

# import the exercise classes so that I can make a list populated with those 
# objects

from exercise import Generic
from exercise import Interval
from exercise import Reps_Based
from exercise import Time_Based


routines = {
     'GMB Wrist': 
          [Time_Based("Wrist Circles, CW",0,30),
          Time_Based("Wrist Circles, CCW",0,30),
          Time_Based("Backwards Wrist Stretch",0,20),
          Time_Based("Backwards Wrist Stretch",0,20),
          Time_Based("Forward Wrist Stretch",0,20),
          Time_Based("Forward Wrist Stretch",0,20),
          Time_Based("Heel Palm Up, Side to Side",0,15),
          Time_Based("Wrist Shakes",0,25),
          Time_Based("Wrist Pulses",0,20),
          Reps_Based("Back of Wrist Extension",0,10),
          Reps_Based("Back of Wrist Extension",0,10),
          Reps_Based("Seal Walk",0,10),
          Reps_Based("Seal Walk",0,10),
          Time_Based("Rear Facing Wrist Hold",0,5)],
     'Rehab Mobility':
          [Time_Based("Elevated Ankle Dorsiflexion, Right",0,60),
          Time_Based("Plantar Fascia Mobilization",0,60),
          Reps_Based("Heel Raises w/ Counter Support",0,30), 
          Time_Based("Rest",0,30), #Set 1
          Reps_Based("Heel Raises w/ Counter Support",0,30), 
          Time_Based("Rest",0,30), #Set 2
          Reps_Based("Heel Raises w/ Counter Support",0,30)
          ],
     'Mobility A': 
          [Time_Based("Forward Fold",0,60),
          Time_Based("Bow Stretch, Left",0,60),
          Time_Based("Bow Stretch, Right",0,60),
          Time_Based("Lying Spine Twist, Left",0,60),
          Time_Based("Lying Spine Twist, Right",0,60),
          Reps_Based("MacKenzie Extensions",0,10)],
     'Rehab Strength': 
          [Reps_Based("Banded Side Step","vLight",20), #Set 1
          Reps_Based("Forward T",0,8),
          Reps_Based("Step up",0,12),
          Reps_Based("Reverse Lunge Squat",0,10),
          Reps_Based("Banded Side Step","vLight",20),#Set 2
          Reps_Based("Forward T",0,8),
          Reps_Based("Step up",0,12),
          Reps_Based("Reverse Lunge Squat",0,10),
          Reps_Based("Banded Side Step","vLight",20), #Set 3
          Reps_Based("Forward T",0,8),
          Reps_Based("Step up",0,12),
          Reps_Based("Reverse Lunge Squat",0,10)],          
     'Wrist Strength': 
          [Reps_Based("Wrist Extensions, Left", 6,10),
          Reps_Based("Wrist Extensions, Right", 6,10),
          Reps_Based("Wrist Extensions, Left", 6,10),
          Reps_Based("Wrist Extensions, Right", 6,10),
          Reps_Based("Wrist Extensions, Left", 6,10),
          Reps_Based("Wrist Extensions, Right", 6,10),
          Reps_Based("Hammer Twist, Left",6,10),
          Reps_Based("Hammer Twist, Right",6,10),
          Reps_Based("Hammer Twists, Left",6,10),
          Reps_Based("Hammer Twist, Right",6,10),
          Reps_Based("Hammer Twists, Left",6,10),
          Reps_Based("Hammer Twist, Right",6,10)],
     'Banded Iso Strength': 
          [Time_Based("Plank on Elbows",0,45),
          Reps_Based("Lying Side Leg Raise, Left","Bodyweight",10),
          Reps_Based("Lying Side Leg Leg, Right","Bodyweight",10),
          Time_Based("Banded Bridge","Medium Band",45),
          Time_Based("Banded Narrow Knees","Light Band",45),
          Time_Based("Banded Back Neck Hold","Light Band",45),
          Time_Based("Banded Front Neck Hold","Light Band",45),
          Time_Based("Banded Front Raise","Light Band",45),
          Time_Based("Banded Chest Press","Medium Heavy Band",45),
          Time_Based("Banded Row","Medium Heavy Band",45),
          Time_Based("Left Plank","Body Weight",45),
          Time_Based("Right Plank","Body Weight",45)],
     'MTBS Banded P1': [Time_Based("Plank","Bodyweight",45),
          Reps_Based("Lying Side Leg Raise, Left","Bodyweight",10),
          Reps_Based("Lying Side Leg Leg, Right","Bodyweight",10),
          Time_Based("Banded Bridge","Medium Band",45),
          Time_Based("Banded Narrow Knees","Light Band",45),
          Time_Based("Banded Back Neck","Light Band",45),
          Time_Based("Banded Back Neck Hold","Light Band",45),
          Time_Based("Banded Front Raise","Light Band",45),
          Time_Based("Banded Deadlift","Medium Heavy Band",45),
          Time_Based("Banded Chest Press","Medium Heavy Band",45),
          Time_Based("Banded Squat","Body Weight",45),
          Time_Based("Banded Row","Medium Heavy Band",45),
          Time_Based("Left Plank","Body Weight",45),
          Time_Based("Right Plank","Body Weight",45)],
     'MTBS Hip Mobility': [Generic("Cycling Recovery","Theragun","See App"),
                    Generic("Glutes","Theragun","See App"),
                    Reps_Based("Frog Stretch","Body Weight",8),
          Reps_Based("Kneeling Lunge Stretch, Left","Body Weight",10),
          Reps_Based("Kneeling Lunge Stretch, Right","Body Weight",10),
                    Reps_Based("Childs Pose to Up Dog","Body Weight",5),
                    Reps_Based("Hamstring Stretch, Center->Cross->Out, Left",
                               "Body Weight",10),
                    Reps_Based("Hamstring Stretch, Center->Cross->Out, Right",
                               "Body Weight",10),
                    Reps_Based("Bow Stretch, Left","Body Weight",5),
                    Reps_Based("Bow Stretch, Right","Body Weight",5),
          Reps_Based("Seated Windshield Wiper, Left","Body Weight",5),
          Reps_Based("Seated Windshield Wiper, Right","Body Weight",5),
                    Reps_Based("Active Leg Lower, Left","Body Weight",5),
                    Reps_Based("Active Leg Lower, Right","Body Weight",5),
                    Reps_Based("Toe Touch, Raised Heels","Body Weight",10),
                    Reps_Based("Toe Touch, Raised Toes","Body Weight",10)],
     'Ramping Iso Strength': [Time_Based("Plank on Elbows",0,45),
          Reps_Based("Lying Side Leg Raise, Left","Bodyweight",10),
          Reps_Based("Lying Side Leg Leg, Right","Bodyweight",10),
          Interval("Iso Bridge",["Press", "Press", "Press"],
                         ["50%","80%","110%"],[20,10,5]),
          Interval("Iso Narrow Knees",["Press", "Press", "Press"],
                         ["50%","80%","110%"],[20,10,5]),
          Interval("Iso Neck Triceps Extension",["Press","Press","Press"],
                         ["50%","80%","110%"],[20,10,5]),
          Interval("Iso Butterfly Crunch",["Press", "Press", "Press"],
                         ["50%","80%","110%"],[20,10,5]),
          Interval("Iso Front Raise",["Press", "Press", "Press"],
                         ["50%","80%","110%"],[20,10,5]),
          Interval("Iso Chest Press",["Press", "Press", "Press"],
                         ["50%","80%","110%"],[20,10,5]),
          Interval("Iso Row",["Press", "Press", "Press"],
                         ["50%","80%","110%"],[20,10,5]),
          Time_Based("Left Plank","Body Weight",45),
          Time_Based("Right Plank","Body Weight",45)],
     'MTBS Ramping P1': [Time_Based("Plank","Bodyweight",45),
          Reps_Based("Lying Side Leg Raise, Left","Bodyweight",10),
          Reps_Based("Lying Side Leg Leg, Right","Bodyweight",10),
          Interval("Iso Bridge",["Press", "Press", "Press"],
                           ["50%","80%","110%"],[20,10,5]),
          Interval("Iso Narrow Knees",["Press", "Press", "Press"],
                           ["50%","80%","110%"],[20,10,5]),
          Interval("Iso Neck Triceps Extension",["Press", "Press", "Press"],
                           ["50%","80%","110%"],[20,10,5]),
          Interval("Iso Butterfly Crunch",["Press", "Press", "Press"],
                           ["50%","80%","110%"],[20,10,5]),
          Interval("Iso Front Raise",["Press", "Press", "Press"],
                           ["50%","80%","110%"],[20,10,5]),
          Interval("Iso Deadlift",["Press", "Press", "Press"],
                           ["50%","80%","110%"],[20,10,5]),
          Interval("Iso Chest Press",["Press", "Press", "Press"],
                           ["50%","80%","110%"],[20,10,5]),
          Interval("Iso Squat",["Press", "Press", "Press"],
                           ["50%","80%","110%"],[20,10,5]),
          Interval("Iso Row",["Press", "Press", "Press"],
                           ["50%","80%","110%"],[20,10,5]),
          Time_Based("Left Plank","Body Weight",45),
          Time_Based("Right Plank","Body Weight",45)], 
     'MTBS Shoulder Mobility': [Generic("Shoulders","Theragun","See App"),
          Generic("Triceps","Theragun","See App"),
                                    Reps_Based("Hold the Wall, Left","BW",5),
                                    Reps_Based("Hold the Wall, Right","BW",5),
          Reps_Based("Overhead Shoulder, Left","BW",5),
          Reps_Based("Overhead Shoulder, Right","BW",5),
                                    Reps_Based("Lats Stretch, Left","BW",5),
                                    Reps_Based("Last Stretch, Right","BW",5),
                                    Reps_Based("Rib Pull, Left","BW",5),
                                    Reps_Based("Rib Pull, Right","BW",5),
          Reps_Based("Half Kneeling T Spine Twist","BW",5),
          Reps_Based("Half Kneeling T Spine Twist, Right","BW",5)],     
     'TR Trainer Work': [Generic("Trainer Road Workout","Bike",
          "Open the TR App")]
}